# Generated by Django 2.1.1 on 2018-12-13 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('contract_name', models.CharField(max_length=32)),
                ('contract_id', models.IntegerField(primary_key=True, serialize=False)),
                ('contract_description', models.CharField(max_length=128)),
                ('contract_create_time', models.DateTimeField()),
                ('contract_status', models.IntegerField()),
                ('contract_begin_time', models.DateTimeField()),
                ('contract_end_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ContractAppendix',
            fields=[
                ('file_id', models.IntegerField(primary_key=True, serialize=False)),
                ('file_url', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=32)),
                ('customer_addr', models.CharField(max_length=128)),
                ('customer_tel', models.CharField(max_length=32)),
                ('customer_fax', models.CharField(max_length=32)),
                ('customer_post', models.CharField(max_length=32)),
                ('customer_bank', models.CharField(max_length=32)),
                ('customer_account', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OperationHistroy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('op_type', models.IntegerField()),
                ('context', models.CharField(max_length=128)),
                ('op_time', models.DateTimeField()),
                ('contract_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_related_operation', to='manager.Contract')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=32)),
                ('role_describe', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='RoleP',
            fields=[
                ('role_id', models.IntegerField(primary_key=True, serialize=False)),
                ('role_permission', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=32)),
                ('user_role_id', models.IntegerField()),
                ('user_password', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='operationhistroy',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_related_operation', to='manager.User'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_consumer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_related_customer', to='manager.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_related_user', to='manager.User'),
        ),
        migrations.AddField(
            model_name='contract',
            name='file_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_related_file', to='manager.ContractAppendix'),
        ),
    ]
